#pragma once

// From glfw3.h
#define TUSK_MOUSE_BUTTON_1         0
#define TUSK_MOUSE_BUTTON_2         1
#define TUSK_MOUSE_BUTTON_3         2
#define TUSK_MOUSE_BUTTON_4         3
#define TUSK_MOUSE_BUTTON_5         4
#define TUSK_MOUSE_BUTTON_6         5
#define TUSK_MOUSE_BUTTON_7         6
#define TUSK_MOUSE_BUTTON_8         7
#define TUSK_MOUSE_BUTTON_LAST      TUSK_MOUSE_BUTTON_8
#define TUSK_MOUSE_BUTTON_LEFT      TUSK_MOUSE_BUTTON_1
#define TUSK_MOUSE_BUTTON_RIGHT     TUSK_MOUSE_BUTTON_2
#define TUSK_MOUSE_BUTTON_MIDDLE    TUSK_MOUSE_BUTTON_3